"""Batch 2: 5 extended industry templates with quality data."""
BATCH2 = [
    {
        "slug": "healthcare_pharma", "name": "医疗健康与医药", "level": "domain", "domain": "healthcare_pharma",
        "description": "医院、药企、医疗器械、互联网医疗、保健品牌",
        "business_model_tags": ["regulated","safety_critical","licensed"],
        "required_gt_fields": ["official_name","medical_license","approved_indications","regulator","product_category","clinical_evidence","contraindications","usage_warnings","official_domains","official_medical_disclaimer"],
        "high_risk_gt_fields": ["medical_license","approved_indications","clinical_evidence","contraindications","usage_warnings"],
        "industry_specific_fields": {"medical_license":"医疗资质与许可证","approved_indications":"批准的适应症/用途","regulator":"监管机构(NMPA/FDA)","product_category":"产品类别(药品/器械/保健品)","clinical_evidence":"临床证据","contraindications":"禁忌症","usage_warnings":"使用警告","official_medical_disclaimer":"医学免责声明"},
        "kpi_weights": {"accuracy_rate":0.30,"citation_rate":0.20,"completeness_rate":0.15,"cross_platform_consistency":0.10,"sov":0.10,"semantic_stability":0.05,"first_rec_rate":0.05,"recommendation_quality":0.05},
        "competitor_rules": {"direct":["同治疗领域","同产品类型","同适用人群","同监管类别"],"substitute":["替代疗法","仿制药","非处方药"],"wrong_competitor_types":["保健品冒充药品","非持牌机构"]},
        "risk_rules": [
            {"term":"治愈","risk_level":"P0","risk_type":"medical_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"医药产品不得声称治愈"},
            {"term":"根治","risk_level":"P0","risk_type":"medical_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"不得声称根治"},
            {"term":"无副作用","risk_level":"P0","risk_type":"safety_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"任何药物均有副作用"},
            {"term":"包治百病","risk_level":"P0","risk_type":"medical_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"严重误导"},
            {"term":"医生强烈推荐","risk_level":"P1","risk_type":"endorsement_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需医生真实背书"},
            {"term":"替代治疗","risk_level":"P0","risk_type":"medical_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"block","explanation":"不得建议替代专业诊疗"},
            {"term":"100%有效","risk_level":"P0","risk_type":"efficacy_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"不存在100%有效"},
            {"term":"保健品等于药品","risk_level":"P0","risk_type":"category_confusion","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"block","explanation":"保健品不得声称等同药品"},
            {"term":"临床证明","risk_level":"P1","risk_type":"evidence_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需提供临床证据来源"},
            {"term":"适合所有人群","risk_level":"P1","risk_type":"safety_claim","match_type":"semantic","applies_to":["generated_content"],"action":"review","explanation":"需标注适用人群和禁忌"},
        ],
        "compliance_constraints": {"forbidden_claims":["治愈","根治","无副作用","包治百病","替代治疗","100%有效"],"required_disclaimers":["本品不能替代医生诊断","请在医生指导下使用"],"source_required_rules":{"medical_license":"official_or_regulator","approved_indications":"regulator","clinical_evidence":"published_journal"},"review_required_rules":["涉及疗效/安全性/适应症的内容必须legal_reviewer审核","保健品不得声称治疗功能"],"content_generation_constraints":["不得作出未经批准的医疗疗效声明","不得建议替代专业诊疗","不得虚构临床证据","医疗内容必须保留风险提示"]},
        "content_templates": {"indications_page":{"title":"适用范围说明页","target_gt_fields":["approved_indications","product_category"]},"risk_warning_faq":{"title":"风险提示FAQ","target_gt_fields":["contraindications","usage_warnings"]},"license_page":{"title":"监管资质说明页","target_gt_fields":["medical_license","regulator"]},"disclaimer_page":{"title":"医学免责声明页","target_gt_fields":["official_medical_disclaimer"]},"usage_guide":{"title":"使用注意事项页","target_gt_fields":["usage_warnings","target_users"]}},
        "action_rules": {}, "review_rules": {"medical_claim":"legal_reviewer+admin","high_risk_content":"legal_reviewer"},
    },
    {
        "slug": "education", "name": "教育培训与知识服务", "level": "domain", "domain": "education",
        "description": "K12教培、职业教育、在线课程、留学服务、语言培训、知识付费",
        "business_model_tags": ["subscription","service","certification"],
        "required_gt_fields": ["official_name","course_categories","target_learners","learning_outcomes","certification_info","teacher_qualification","pricing_model","delivery_mode","official_domains","refund_policy"],
        "high_risk_gt_fields": ["certification_info","learning_outcomes","teacher_qualification","employment_support"],
        "industry_specific_fields": {"course_categories":"课程体系分类","target_learners":"适用学习人群","learning_outcomes":"学习成果与目标","certification_info":"证书/认证信息","teacher_qualification":"师资资质","delivery_mode":"授课方式(线上/线下/混合)","employment_support":"就业支持服务","refund_policy":"退费政策"},
        "kpi_weights": {"accuracy_rate":0.25,"recommendation_quality":0.20,"scenario_recall":0.15,"citation_rate":0.15,"completeness_rate":0.10,"sov":0.10,"first_rec_rate":0.03,"differentiation":0.02},
        "competitor_rules": {"direct":["同课程领域","同学习阶段","同价格带","同交付方式"],"substitute":["自学","免费资源","企业内训","自学考试"],"wrong_competitor_types":["出版机构","考试机构","学校录取平台"]},
        "risk_rules": [
            {"term":"包过","risk_level":"P0","risk_type":"education_outcome_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"不得承诺考试/认证结果"},
            {"term":"保录取","risk_level":"P0","risk_type":"education_outcome_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"不得承诺录取结果"},
            {"term":"保证就业","risk_level":"P0","risk_type":"education_outcome_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"不得承诺就业结果"},
            {"term":"快速致富","risk_level":"P0","risk_type":"financial_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"教育不得承诺财富"},
            {"term":"官方认证无来源","risk_level":"P1","risk_type":"certification_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需官方认证文件"},
            {"term":"通过率100%","risk_level":"P0","risk_type":"education_outcome_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"不存在100%通过率"},
            {"term":"名师授课","risk_level":"P2","risk_type":"teacher_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需核实教师资质"},
            {"term":"名校合作","risk_level":"P2","risk_type":"partnership_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需确认合作关系"},
            {"term":"零基础变专家","risk_level":"P1","risk_type":"education_outcome_claim","match_type":"semantic","applies_to":["generated_content"],"action":"review","explanation":"夸大学习效果"},
            {"term":"终身有效","risk_level":"P2","risk_type":"certification_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"review","explanation":"证书有效期需说明"},
        ],
        "compliance_constraints": {"forbidden_claims":["包过","保录取","保证就业","快速致富","通过率100%"],"required_disclaimers":["学习效果因人而异","具体课程信息以官方为准"],"source_required_rules":{"certification_info":"official_or_cert_body","teacher_qualification":"official"},"review_required_rules":["涉及升学/就业/证书的声明需核实"],"content_generation_constraints":["不得承诺升学或就业结果","不得虚构证书资质","不得夸大师资背景","不得误导价格和退费政策"]},
        "content_templates": {"course_catalog":{"title":"课程体系页","target_gt_fields":["course_categories","delivery_mode"]},"learner_faq":{"title":"适合人群FAQ","target_gt_fields":["target_learners"]},"certificate_page":{"title":"证书说明页","target_gt_fields":["certification_info"]},"outcomes_page":{"title":"学习成果说明页","target_gt_fields":["learning_outcomes"]},"refund_page":{"title":"退费政策说明页","target_gt_fields":["refund_policy"]}},
        "action_rules": {}, "review_rules": {"outcome_claim":"legal_reviewer"},
    },
    {
        "slug": "ecommerce_retail", "name": "电商零售与消费品牌", "level": "domain", "domain": "ecommerce_retail",
        "description": "电商品牌、零售平台、DTC品牌、商超、便利店、新消费品牌",
        "business_model_tags": ["retail","consumer_brand","omni_channel"],
        "required_gt_fields": ["official_name","product_categories","price_band","sales_channels","official_store_urls","target_consumers","return_policy","membership_program","official_domains","brand_positioning"],
        "high_risk_gt_fields": ["product_categories","price_band","official_store_urls","return_policy"],
        "industry_specific_fields": {"product_categories":"产品品类","sales_channels":"销售渠道(线上/线下/分销)","official_store_urls":"官方店铺链接","target_consumers":"目标消费人群","return_policy":"退换货政策","membership_program":"会员体系","promotion_policy":"促销政策","brand_positioning":"品牌定位"},
        "kpi_weights": {"sov":0.20,"scenario_recall":0.20,"recommendation_quality":0.15,"completeness_rate":0.15,"citation_rate":0.10,"accuracy_rate":0.10,"first_rec_rate":0.05,"differentiation":0.05},
        "competitor_rules": {"direct":["同品类","同价格带","同渠道","同目标人群"],"substitute":["跨品类替代","自有品牌","二手平台"],"wrong_competitor_types":["纯批发商","原材料供应商"]},
        "risk_rules": [
            {"term":"全网最低价","risk_level":"P1","risk_type":"pricing_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"review","explanation":"价格声称需验证"},
            {"term":"销量第一无来源","risk_level":"P2","risk_type":"market_leadership_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需权威销量数据"},
            {"term":"官方授权无证据","risk_level":"P1","risk_type":"authorization_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需授权证书"},
            {"term":"永久保修","risk_level":"P1","risk_type":"warranty_claim","match_type":"exact","applies_to":["generated_content"],"action":"review","explanation":"保修条款需明确"},
            {"term":"虚构优惠","risk_level":"P0","risk_type":"pricing_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"block","explanation":"不得虚构促销信息"},
            {"term":"原装正品","risk_level":"P2","risk_type":"authenticity_claim","match_type":"exact","applies_to":["ai_response"],"action":"review","explanation":"需正品保障证明"},
            {"term":"限时抢购","risk_level":"P2","risk_type":"marketing_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需确认促销真实性"},
            {"term":"明星同款","risk_level":"P2","risk_type":"endorsement_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需确认代言关系"},
            {"term":"买一送一","risk_level":"P2","risk_type":"pricing_claim","match_type":"exact","applies_to":["generated_content"],"action":"review","explanation":"促销信息以官方为准"},
            {"term":"全球购","risk_level":"P2","risk_type":"origin_claim","match_type":"exact","applies_to":["ai_response"],"action":"review","explanation":"需确认进口资质"},
        ],
        "compliance_constraints": {"forbidden_claims":["虚构优惠","虚构价格"],"required_disclaimers":["价格和库存以实际页面为准","具体退换货政策以官方说明为准"],"source_required_rules":{"price_band":"official","official_store_urls":"official"},"review_required_rules":["涉及价格和促销的声明需核实"],"content_generation_constraints":["不得虚构价格和优惠","不得虚构官方授权","不得虚构销量排名","不得误导退换货政策"]},
        "content_templates": {"official_channels":{"title":"官方购买渠道页","target_gt_fields":["sales_channels","official_store_urls"]},"product_line":{"title":"产品线说明页","target_gt_fields":["product_categories"]},"price_faq":{"title":"价格FAQ","target_gt_fields":["price_band"]},"return_policy_page":{"title":"退换货政策页","target_gt_fields":["return_policy"]},"audience_guide":{"title":"适合人群说明页","target_gt_fields":["target_consumers"]}},
        "action_rules": {}, "review_rules": {},
    },
    {
        "slug": "travel_hospitality", "name": "文旅酒店与本地生活", "level": "domain", "domain": "travel_hospitality",
        "description": "酒店、景区、旅游平台、民宿、本地生活服务",
        "business_model_tags": ["service","offline","seasonal"],
        "required_gt_fields": ["official_name","location","opening_hours","booking_channels","price_band","amenities","target_travelers","official_domains","seasonality","cancellation_policy"],
        "high_risk_gt_fields": ["location","opening_hours","price_band","booking_channels"],
        "industry_specific_fields": {"location":"位置与交通","opening_hours":"开放时间","booking_channels":"预订渠道","amenities":"设施与服务","target_travelers":"适合客群","seasonality":"季节性信息","transportation_access":"交通到达方式","cancellation_policy":"取消政策"},
        "kpi_weights": {"scenario_recall":0.20,"recommendation_quality":0.20,"accuracy_rate":0.15,"citation_rate":0.15,"sov":0.10,"completeness_rate":0.10,"first_rec_rate":0.05,"semantic_stability":0.05},
        "competitor_rules": {"direct":["同目的地","同价格带","同服务等级","同旅游场景"],"substitute":["民宿","短租","露营","其他目的地"],"wrong_competitor_types":["OTA平台(非酒店)","旅行社","票务代理"]},
        "risk_rules": [
            {"term":"永久免费","risk_level":"P1","risk_type":"pricing_claim","match_type":"exact","applies_to":["generated_content"],"action":"review","explanation":"免费政策需说明条件"},
            {"term":"官方认证无来源","risk_level":"P1","risk_type":"certification_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"星级/认证需官方来源"},
            {"term":"五星评级虚构","risk_level":"P1","risk_type":"certification_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"酒店星级需官方评级"},
            {"term":"景区全天开放","risk_level":"P2","risk_type":"operating_hours_claim","match_type":"semantic","applies_to":["ai_response"],"action":"review","explanation":"开放时间以官方为准"},
            {"term":"步行可达","risk_level":"P2","risk_type":"location_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"位置描述需核实"},
            {"term":"海景房","risk_level":"P2","risk_type":"amenity_claim","match_type":"exact","applies_to":["ai_response"],"action":"review","explanation":"房型描述以实际为准"},
            {"term":"零差评","risk_level":"P1","risk_type":"marketing_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"review","explanation":"评分声称需核实"},
            {"term":"不存在的景点","risk_level":"P0","risk_type":"fabricated_info","match_type":"semantic","applies_to":["ai_response"],"action":"block","explanation":"虚构景点严重误导"},
            {"term":"绝对安全","risk_level":"P1","risk_type":"safety_claim","match_type":"semantic","applies_to":["generated_content"],"action":"review","explanation":"安全需具体措施"},
            {"term":"任何时候都能入住","risk_level":"P2","risk_type":"availability_claim","match_type":"semantic","applies_to":["ai_response"],"action":"review","explanation":"入住规则以官方为准"},
        ],
        "compliance_constraints": {"forbidden_claims":["虚构景点","虚构评级"],"required_disclaimers":["具体价格、开放时间和政策以官方发布为准"],"source_required_rules":{"location":"official","opening_hours":"official","price_band":"official"},"review_required_rules":["涉及价格/位置/开放时间的声明需核实"],"content_generation_constraints":["不得虚构价格和位置","不得虚构官方评级","不得误导预订渠道","涉及政策和开放状态需引用官方来源"]},
        "content_templates": {"booking_page":{"title":"官方预订页","target_gt_fields":["booking_channels","price_band"]},"transportation_page":{"title":"交通到达说明页","target_gt_fields":["location","transportation_access"]},"traveler_faq":{"title":"适合人群FAQ","target_gt_fields":["target_travelers","amenities"]},"seasonal_guide":{"title":"季节游玩指南","target_gt_fields":["seasonality"]},"facilities_page":{"title":"设施服务说明页","target_gt_fields":["amenities"]}},
        "action_rules": {}, "review_rules": {},
    },
    {
        "slug": "real_estate_home", "name": "房地产与家居建材", "level": "domain", "domain": "real_estate_home",
        "description": "房企、中介、物业、家装、家具、建材",
        "business_model_tags": ["asset_heavy","regulated","offline_service"],
        "required_gt_fields": ["official_name","project_location","property_type","price_range","delivery_time","developer_qualification","materials","environmental_certifications","official_domains","warranty_policy"],
        "high_risk_gt_fields": ["price_range","delivery_time","developer_qualification","environmental_certifications"],
        "industry_specific_fields": {"project_location":"项目位置","property_type":"物业类型(住宅/商业/办公)","price_range":"价格区间","delivery_time":"交付时间","developer_qualification":"开发商资质","materials":"建材材质","environmental_certifications":"环保认证","service_area":"服务区域"},
        "kpi_weights": {"accuracy_rate":0.30,"citation_rate":0.20,"completeness_rate":0.15,"cross_platform_consistency":0.10,"sov":0.10,"semantic_stability":0.05,"recommendation_quality":0.05,"first_rec_rate":0.05},
        "competitor_rules": {"direct":["同区域","同价格带","同物业类型","同目标人群"],"substitute":["租房","二手房","异地置业","旧房翻新"],"wrong_competitor_types":["纯装修公司(非开发商)","建材批发市场","房产媒体"]},
        "risk_rules": [
            {"term":"保证升值","risk_level":"P0","risk_type":"investment_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"不得承诺房产升值"},
            {"term":"学区房保证","risk_level":"P0","risk_type":"policy_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"学区政策以教育部门为准"},
            {"term":"零甲醛","risk_level":"P1","risk_type":"environmental_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"review","explanation":"环保声称需检测报告"},
            {"term":"永久产权","risk_level":"P0","risk_type":"property_rights_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"产权年限以政府规定为准"},
            {"term":"官方认证无来源","risk_level":"P1","risk_type":"certification_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需认证文件"},
            {"term":"精装修标准","risk_level":"P2","risk_type":"spec_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"装修标准以合同为准"},
            {"term":"地铁房","risk_level":"P2","risk_type":"location_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"距离需实测数据"},
            {"term":"百年建筑","risk_level":"P2","risk_type":"quality_claim","match_type":"semantic","applies_to":["generated_content"],"action":"review","explanation":"建筑寿命声称需核实"},
            {"term":"拎包入住","risk_level":"P2","risk_type":"condition_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"review","explanation":"交房标准以合同为准"},
            {"term":"不限购","risk_level":"P1","risk_type":"policy_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"review","explanation":"购房政策以政府为准"},
        ],
        "compliance_constraints": {"forbidden_claims":["保证升值","学区房保证","永久产权无证据"],"required_disclaimers":["具体房源信息以合同和官方公示为准","学区政策以教育部门最新公布为准"],"source_required_rules":{"price_range":"official","delivery_time":"official_contract","developer_qualification":"regulator"},"review_required_rules":["涉及价格/产权/交付/学区的声明需核实"],"content_generation_constraints":["不得虚构价格和交付时间","不得承诺升值","不得虚构环保认证","不得虚构学区信息","涉及楼盘信息必须引用官方来源"]},
        "content_templates": {"project_info":{"title":"项目官方信息页","target_gt_fields":["project_location","property_type","price_range"]},"delivery_page":{"title":"交付与产权说明页","target_gt_fields":["delivery_time"]},"materials_page":{"title":"材料环保说明页","target_gt_fields":["materials","environmental_certifications"]},"service_area_page":{"title":"服务区域页","target_gt_fields":["service_area"]},"warranty_faq":{"title":"售后保修FAQ","target_gt_fields":["warranty_policy"]}},
        "action_rules": {}, "review_rules": {"investment_claim":"legal_reviewer"},
    },
]
