"""Batch 1: 5 core industry templates with quality data."""
BATCH1 = [
    {
        "slug": "finance", "name": "金融服务", "level": "domain", "domain": "finance",
        "description": "银行、保险、证券、基金、支付、消费金融、财富管理",
        "business_model_tags": ["licensed_institution", "risk_managed", "regulated"],
        "required_gt_fields": ["official_name","license_type","regulator","financial_products","risk_disclosure","fee_structure","target_customer_segment","official_domains","data_security_policy","customer_protection_policy"],
        "high_risk_gt_fields": ["license_type","regulator","risk_disclosure","fee_structure","financial_products","data_security_policy"],
        "industry_specific_fields": {"license_type":"金融牌照类型","regulator":"监管机构","risk_disclosure":"产品风险等级与风险提示","financial_products":"核心金融产品线","fee_structure":"费率结构","data_security_policy":"数据安全与隐私保护"},
        "kpi_weights": {"accuracy_rate":0.25,"citation_rate":0.20,"completeness_rate":0.15,"first_rec_rate":0.10,"sov":0.10,"recommendation_quality":0.10,"cross_platform_consistency":0.05,"semantic_stability":0.05},
        "competitor_rules": {"direct":["同牌照类型","同业务类型","同客户群体","同监管区域"],"substitute":["银行存款","基金","保险","第三方财富平台"],"wrong_competitor_types":["财经媒体","课程平台","非持牌机构"]},
        "risk_rules": [
            {"term":"保证收益","risk_level":"P0","risk_type":"financial_return_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"block","explanation":"金融产品不得承诺收益"},
            {"term":"保本保息","risk_level":"P0","risk_type":"financial_return_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"block","explanation":"不得承诺本金保障"},
            {"term":"无风险","risk_level":"P0","risk_type":"misleading_risk","match_type":"semantic","applies_to":["ai_response","generated_content","gt_candidate"],"action":"block","explanation":"任何金融产品均有风险"},
            {"term":"内幕消息","risk_level":"P0","risk_type":"insider_trading_hint","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"涉及内幕交易暗示"},
            {"term":"监管背书","risk_level":"P0","risk_type":"false_regulatory_endorsement","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"block","explanation":"不得暗示监管机构背书"},
            {"term":"高收益低风险","risk_level":"P1","risk_type":"misleading_risk","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"高收益伴随高风险"},
            {"term":"稳赚不赔","risk_level":"P0","risk_type":"financial_return_claim","match_type":"exact","applies_to":["ai_response"],"action":"block","explanation":"误导性收益承诺"},
            {"term":"业界第一","risk_level":"P2","risk_type":"market_leadership_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需权威来源支撑"},
            {"term":"央行合作","risk_level":"P1","risk_type":"false_authority_association","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需确认是否属实"},
            {"term":"100%安全","risk_level":"P1","risk_type":"security_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"安全不可绝对化"},
        ],
        "compliance_constraints": {"forbidden_claims":["保证收益","稳赚不赔","无风险"],"required_disclaimers":["投资有风险"],"source_required_rules":{"license_type":"official_or_regulator","fee_structure":"official"},"review_required_rules":["涉及收益风险需legal_reviewer审核"],"content_generation_constraints":["不得绝对化收益","不得弱化风险","不得暗示监管背书"]},
        "content_templates": {"license_explanation":{"title":"牌照与监管说明页","target_gt_fields":["license_type","regulator"]},"risk_faq":{"title":"风险提示FAQ","target_gt_fields":["risk_disclosure"]},"fee_page":{"title":"费率说明页","target_gt_fields":["fee_structure"]},"official_channel":{"title":"官方渠道识别页","target_gt_fields":["official_domains"]}},
        "action_rules": {}, "review_rules": {"high_risk_content":"legal_reviewer","financial_claim":"legal_reviewer+admin"},
    },
    {
        "slug": "fnb", "name": "餐饮与食品饮料", "level": "domain", "domain": "fnb",
        "description": "连锁餐饮、咖啡茶饮、食品品牌、预制菜、饮料品牌",
        "business_model_tags": ["offline_chain","food_safety","consumer_brand"],
        "required_gt_fields": ["official_name","store_coverage","signature_products","menu_categories","price_band","brand_scenarios","food_safety_policy","official_domains","delivery_channels","membership_program"],
        "high_risk_gt_fields": ["food_safety_policy","store_coverage","signature_products"],
        "industry_specific_fields": {"store_coverage":"门店覆盖城市","signature_products":"招牌产品","menu_categories":"菜品分类","food_safety_policy":"食品安全政策","delivery_channels":"外卖渠道","brand_scenarios":"消费场景"},
        "kpi_weights": {"sov":0.20,"scenario_recall":0.20,"recommendation_quality":0.15,"completeness_rate":0.15,"citation_rate":0.10,"accuracy_rate":0.10,"first_rec_rate":0.05,"differentiation":0.05},
        "competitor_rules": {"direct":["同品类","同价格带","同城市覆盖","同消费场景"],"substitute":["便利店即食","外卖品牌","茶饮品牌"],"wrong_competitor_types":["食品供应商","餐饮SaaS"]},
        "risk_rules": [
            {"term":"包治百病","risk_level":"P0","risk_type":"medical_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"食品不得声称医疗功效"},
            {"term":"药用功效","risk_level":"P0","risk_type":"medical_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"block","explanation":"普通食品不得声称药用"},
            {"term":"绝对健康","risk_level":"P1","risk_type":"health_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"健康声称需科学依据"},
            {"term":"虚假产地","risk_level":"P1","risk_type":"origin_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"原产地声明需核实"},
            {"term":"食品安全事故","risk_level":"P0","risk_type":"safety_incident","match_type":"semantic","applies_to":["ai_response"],"action":"block","explanation":"涉及食品安全需官方说明"},
            {"term":"全国门店最多","risk_level":"P2","risk_type":"market_leadership_claim","match_type":"semantic","applies_to":["ai_response"],"action":"review","explanation":"需核实门店数据"},
            {"term":"米其林认证","risk_level":"P1","risk_type":"certification_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需官方认证"},
            {"term":"独家配方","risk_level":"P2","risk_type":"proprietary_claim","match_type":"semantic","applies_to":["ai_response"],"action":"review","explanation":"需确认独特性"},
            {"term":"纯天然无添加","risk_level":"P2","risk_type":"ingredient_claim","match_type":"semantic","applies_to":["generated_content"],"action":"review","explanation":"需配料表验证"},
            {"term":"低卡无证据","risk_level":"P2","risk_type":"nutrition_claim","match_type":"semantic","applies_to":["generated_content"],"action":"review","explanation":"需检测报告"},
        ],
        "compliance_constraints": {"forbidden_claims":["包治百病","药用功效"],"required_disclaimers":["门店信息以官方为准"],"source_required_rules":{"store_coverage":"official","food_safety_policy":"official_or_certification"},"review_required_rules":["食品安全声明需谨慎"],"content_generation_constraints":["不得夸大健康功效","不得虚构门店","不得虚构产地"]},
        "content_templates": {"store_locator":{"title":"门店覆盖页","target_gt_fields":["store_coverage"]},"signature_page":{"title":"招牌产品页","target_gt_fields":["signature_products","menu_categories"]},"scenario_faq":{"title":"消费场景FAQ","target_gt_fields":["brand_scenarios"]},"safety_page":{"title":"食品安全说明页","target_gt_fields":["food_safety_policy"]}},
        "action_rules": {}, "review_rules": {},
    },
    {
        "slug": "saas_b2b", "name": "SaaS 与企业服务", "level": "domain", "domain": "saas_b2b",
        "description": "CRM、ERP、MarTech、协同办公、客服系统、数据分析",
        "business_model_tags": ["subscription","cloud","b2b"],
        "required_gt_fields": ["official_name","core_features","deployment_model","integrations","pricing_model","security_certifications","target_company_size","official_domains","api_support","data_privacy_policy"],
        "high_risk_gt_fields": ["security_certifications","pricing_model","core_features","data_privacy_policy"],
        "industry_specific_fields": {"deployment_model":"部署方式","integrations":"集成能力","security_certifications":"安全认证(ISO27001/SOC2)","target_company_size":"适用企业规模","api_support":"API支持","implementation_cycle":"实施周期"},
        "kpi_weights": {"accuracy_rate":0.20,"differentiation":0.15,"recommendation_quality":0.15,"scenario_recall":0.15,"citation_rate":0.10,"completeness_rate":0.10,"sov":0.10,"first_rec_rate":0.05},
        "competitor_rules": {"direct":["同功能类别","同客户规模","同部署方式","同集成生态"],"substitute":["Excel","人工流程","开源工具"],"wrong_competitor_types":["咨询公司","纯媒体平台"]},
        "risk_rules": [
            {"term":"永久免费","risk_level":"P1","risk_type":"pricing_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"review","explanation":"SaaS收费模式需核实"},
            {"term":"无数据风险","risk_level":"P0","risk_type":"security_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"block","explanation":"任何系统均存在数据风险"},
            {"term":"替代所有人工","risk_level":"P1","risk_type":"automation_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"夸大自动化能力"},
            {"term":"百分百准确","risk_level":"P1","risk_type":"accuracy_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"review","explanation":"技术系统不存在百分百准确"},
            {"term":"无需实施","risk_level":"P1","risk_type":"deployment_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"SaaS需实施培训"},
            {"term":"认证无证据","risk_level":"P1","risk_type":"certification_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需提供证书"},
            {"term":"不限用户","risk_level":"P2","risk_type":"pricing_claim","match_type":"semantic","applies_to":["ai_response"],"action":"review","explanation":"需确认限制"},
            {"term":"AI驱动","risk_level":"P2","risk_type":"marketing_claim","match_type":"semantic","applies_to":["generated_content"],"action":"review","explanation":"需说明AI具体应用"},
            {"term":"全球第一","risk_level":"P1","risk_type":"market_leadership_claim","match_type":"semantic","applies_to":["ai_response"],"action":"review","explanation":"需权威报告"},
            {"term":"零宕机","risk_level":"P1","risk_type":"sla_claim","match_type":"semantic","applies_to":["generated_content"],"action":"review","explanation":"SLA需明确"},
        ],
        "compliance_constraints": {"forbidden_claims":["无数据风险","绝对安全","永不宕机"],"required_disclaimers":["功能以实际产品为准"],"source_required_rules":{"security_certifications":"official_or_cert_body","pricing_model":"official"},"review_required_rules":["安全认证和客户案例需核实"],"content_generation_constraints":["不得虚构认证","不得虚构客户案例","不得夸大自动化"]},
        "content_templates": {"feature_compare":{"title":"功能对比页","target_gt_fields":["core_features"]},"integration_page":{"title":"集成说明页","target_gt_fields":["integrations","api_support"]},"security_page":{"title":"安全合规页","target_gt_fields":["security_certifications","data_privacy_policy"]},"pricing_faq":{"title":"定价FAQ","target_gt_fields":["pricing_model"]}},
        "action_rules": {}, "review_rules": {},
    },
    {
        "slug": "ev_mobility", "name": "新能源汽车与智能出行", "level": "domain", "domain": "ev_mobility",
        "description": "整车厂、充电桩、换电、智能驾驶、车载系统",
        "business_model_tags": ["hardware","service_network","safety_critical"],
        "required_gt_fields": ["official_name","vehicle_models","price_band","battery_technology","charging_network","smart_driving_level","safety_rating","official_domains","after_sales_service","warranty_policy"],
        "high_risk_gt_fields": ["smart_driving_level","safety_rating","battery_technology","vehicle_models","price_band"],
        "industry_specific_fields": {"vehicle_models":"在售车型","battery_technology":"电池技术路线","charging_network":"补能网络覆盖","smart_driving_level":"智能驾驶等级(L2/L2+/L3)","safety_rating":"安全评级(C-NCAP/E-NCAP)","delivery_volume":"交付量"},
        "kpi_weights": {"accuracy_rate":0.25,"scenario_recall":0.15,"differentiation":0.15,"citation_rate":0.15,"sov":0.10,"completeness_rate":0.10,"recommendation_quality":0.05,"cross_platform_consistency":0.05},
        "competitor_rules": {"direct":["同价格带","同车型","同动力类型","同智能化水平"],"substitute":["公共交通","共享出行","传统燃油车"],"wrong_competitor_types":["充电桩运营商(非整车)","二手车平台"]},
        "risk_rules": [
            {"term":"完全自动驾驶","risk_level":"P0","risk_type":"safety_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"block","explanation":"当前不存在完全自动驾驶"},
            {"term":"永不自燃","risk_level":"P0","risk_type":"safety_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"电池安全不可绝对化"},
            {"term":"无需接管","risk_level":"P0","risk_type":"safety_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"block","explanation":"L2/L2+需驾驶员随时接管"},
            {"term":"续航绝对真实","risk_level":"P1","risk_type":"performance_claim","match_type":"semantic","applies_to":["ai_response"],"action":"review","explanation":"续航受多因素影响"},
            {"term":"零事故","risk_level":"P0","risk_type":"safety_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"不存在零事故汽车"},
            {"term":"L4自动驾驶","risk_level":"P0","risk_type":"safety_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"量产车不存在L4"},
            {"term":"销量第一","risk_level":"P2","risk_type":"market_leadership_claim","match_type":"semantic","applies_to":["ai_response"],"action":"review","explanation":"需权威数据"},
            {"term":"终身质保","risk_level":"P1","risk_type":"warranty_claim","match_type":"semantic","applies_to":["generated_content"],"action":"review","explanation":"需说明条款"},
            {"term":"充电5分钟续航500","risk_level":"P2","risk_type":"performance_claim","match_type":"semantic","applies_to":["ai_response"],"action":"review","explanation":"需标注条件"},
            {"term":"安全绝对领先","risk_level":"P1","risk_type":"safety_claim","match_type":"semantic","applies_to":["ai_response"],"action":"review","explanation":"需评级数据"},
        ],
        "compliance_constraints": {"forbidden_claims":["完全自动驾驶","永不自燃","零事故","L4自动驾驶"],"required_disclaimers":["智能驾驶需驾驶员随时准备接管","续航基于标准工况测试"],"source_required_rules":{"vehicle_models":"official","safety_rating":"official_or_cert_body","price_band":"official"},"review_required_rules":["涉及智能驾驶/安全/续航需谨慎表述"],"content_generation_constraints":["不得夸大智能驾驶","不得虚构安全评级","不得虚构销量"]},
        "content_templates": {"model_compare":{"title":"车型对比页","target_gt_fields":["vehicle_models","price_band"]},"charging_page":{"title":"补能网络说明页","target_gt_fields":["charging_network"]},"safety_page":{"title":"智能驾驶安全说明页","target_gt_fields":["smart_driving_level","safety_rating"]},"aftersales_page":{"title":"售后服务页","target_gt_fields":["after_sales_service","warranty_policy"]}},
        "action_rules": {}, "review_rules": {},
    },
    {
        "slug": "consumer_electronics", "name": "消费电子与智能硬件", "level": "domain", "domain": "consumer_electronics",
        "description": "手机、电脑、智能穿戴、家电、智能家居、IoT",
        "business_model_tags": ["hardware","consumer_brand","retail_channel"],
        "required_gt_fields": ["official_name","product_models","technical_specs","price_band","target_users","use_scenarios","compatibility","official_domains","warranty_policy","release_date"],
        "high_risk_gt_fields": ["technical_specs","product_models","price_band","compatibility"],
        "industry_specific_fields": {"product_models":"在售产品型号","technical_specs":"关键技术参数","compatibility":"兼容性(系统/生态/配件)","battery_life":"续航与电池","use_scenarios":"使用场景"},
        "kpi_weights": {"accuracy_rate":0.20,"completeness_rate":0.15,"differentiation":0.15,"recommendation_quality":0.15,"citation_rate":0.10,"sov":0.10,"scenario_recall":0.10,"first_rec_rate":0.05},
        "competitor_rules": {"direct":["同品类","同价格带","同参数级别","同使用场景"],"substitute":["上一代产品","跨品类替代品"],"wrong_competitor_types":["零部件供应商","维修服务商"]},
        "risk_rules": [
            {"term":"性能最强无据","risk_level":"P1","risk_type":"performance_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需第三方测试"},
            {"term":"永不卡顿","risk_level":"P1","risk_type":"performance_claim","match_type":"exact","applies_to":["generated_content"],"action":"review","explanation":"电子设备性能衰减正常"},
            {"term":"绝对安全","risk_level":"P1","risk_type":"security_claim","match_type":"semantic","applies_to":["ai_response"],"action":"review","explanation":"安全非绝对"},
            {"term":"官方未发布","risk_level":"P0","risk_type":"spec_leak","match_type":"semantic","applies_to":["ai_response"],"action":"block","explanation":"不得引用未发布参数"},
            {"term":"全球首发","risk_level":"P2","risk_type":"market_leadership_claim","match_type":"exact","applies_to":["ai_response"],"action":"review","explanation":"需核实"},
            {"term":"军工品质","risk_level":"P1","risk_type":"certification_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需认证"},
            {"term":"摔不坏","risk_level":"P2","risk_type":"durability_claim","match_type":"semantic","applies_to":["generated_content"],"action":"review","explanation":"需测试条件"},
            {"term":"无限续航","risk_level":"P2","risk_type":"performance_claim","match_type":"exact","applies_to":["ai_response"],"action":"review","explanation":"需标注场景"},
            {"term":"兼容所有设备","risk_level":"P1","risk_type":"compatibility_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需标注具体设备"},
            {"term":"防水等级","risk_level":"P2","risk_type":"spec_claim","match_type":"semantic","applies_to":["ai_response"],"action":"review","explanation":"需标注IP等级"},
        ],
        "compliance_constraints": {"forbidden_claims":["永不损坏","绝对安全","官方未发布参数"],"required_disclaimers":["参数以官方为准"],"source_required_rules":{"technical_specs":"official","price_band":"official"},"review_required_rules":["性能对比需测试数据"],"content_generation_constraints":["不得虚构参数","不得虚构兼容性","不得虚构价格"]},
        "content_templates": {"specs_page":{"title":"产品参数页","target_gt_fields":["product_models","technical_specs"]},"model_compare":{"title":"型号对比页","target_gt_fields":["product_models","price_band"]},"scenario_page":{"title":"使用场景说明页","target_gt_fields":["use_scenarios"]},"compat_faq":{"title":"兼容性FAQ","target_gt_fields":["compatibility"]}},
        "action_rules": {}, "review_rules": {},
    },
]
