"""Batch 3: 5 specialized industry templates with quality data."""
BATCH3 = [
    {
        "slug": "industrial_b2b", "name": "工业制造与B2B供应链", "level": "domain", "domain": "industrial_b2b",
        "description": "高端制造、工业设备、零部件、原材料、工厂服务、自动化设备",
        "business_model_tags": ["b2b","heavy_asset","technical"],
        "required_gt_fields": ["official_name","product_specs","certifications","production_capacity","application_industries","manufacturing_process","quality_standards","official_domains","customer_segments","after_sales_service"],
        "high_risk_gt_fields": ["certifications","production_capacity","product_specs","quality_standards"],
        "industry_specific_fields": {"product_specs":"产品技术规格","certifications":"认证(ISO/CE/UL/国标)","production_capacity":"产能规模","application_industries":"适用行业","manufacturing_process":"制造工艺","quality_standards":"质量标准","supply_chain_position":"供应链位置","customer_segments":"客户类型(OEM/ODM/自主品牌)"},
        "kpi_weights": {"accuracy_rate":0.25,"completeness_rate":0.20,"citation_rate":0.15,"differentiation":0.15,"sov":0.10,"scenario_recall":0.05,"recommendation_quality":0.05,"first_rec_rate":0.05},
        "competitor_rules": {"direct":["同工艺","同规格","同应用行业","同供应链环节"],"substitute":["进口替代","新材料","工艺外包"],"wrong_competitor_types":["贸易商","设备租赁商","纯原材料商"]},
        "risk_rules": [
            {"term":"全球第一","risk_level":"P1","risk_type":"market_leadership_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需行业报告支撑"},
            {"term":"军工认证无证据","risk_level":"P0","risk_type":"certification_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"block","explanation":"军工认证极其敏感"},
            {"term":"独家供应","risk_level":"P1","risk_type":"exclusivity_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需客户确认"},
            {"term":"产能虚构","risk_level":"P0","risk_type":"capacity_fabrication","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"block","explanation":"产能数据需可核实"},
            {"term":"客户案例虚构","risk_level":"P0","risk_type":"customer_case_fabrication","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"block","explanation":"客户案例需公开可查"},
            {"term":"零缺陷","risk_level":"P1","risk_type":"quality_claim","match_type":"exact","applies_to":["generated_content"],"action":"review","explanation":"不存在零缺陷制造"},
            {"term":"替代进口","risk_level":"P2","risk_type":"substitution_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需技术对标数据"},
            {"term":"自主研发","risk_level":"P2","risk_type":"rnd_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需专利或研发证明"},
            {"term":"Tier1供应商","risk_level":"P2","risk_type":"supply_chain_claim","match_type":"exact","applies_to":["ai_response"],"action":"review","explanation":"需客户确认"},
            {"term":"行业标准制定者","risk_level":"P1","risk_type":"standards_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需标准文件"},
        ],
        "compliance_constraints": {"forbidden_claims":["虚构认证","虚构产能","虚构客户案例"],"required_disclaimers":["技术参数以官方文档为准"],"source_required_rules":{"certifications":"official_or_cert_body","product_specs":"official"},"review_required_rules":["涉及认证/产能/客户的声明需核实"],"content_generation_constraints":["不得虚构认证和客户案例","不得虚构产能","不得夸大供应链地位"]},
        "content_templates": {"specs_page":{"title":"技术参数页","target_gt_fields":["product_specs","quality_standards"]},"applications_page":{"title":"行业应用页","target_gt_fields":["application_industries"]},"certifications_page":{"title":"质量认证页","target_gt_fields":["certifications"]},"supply_chain_page":{"title":"供应链位置说明页","target_gt_fields":["supply_chain_position"]}},
        "action_rules": {}, "review_rules": {},
    },
    {
        "slug": "logistics_crossborder", "name": "物流供应链与跨境贸易", "level": "domain", "domain": "logistics_crossborder",
        "description": "快递、货代、仓储、跨境电商服务、清关服务、海外仓",
        "business_model_tags": ["service_network","crossborder","time_sensitive"],
        "required_gt_fields": ["official_name","service_regions","shipping_lanes","delivery_time_range","customs_clearance_capability","warehouse_network","pricing_model","official_domains","insurance_policy","tracking_system"],
        "high_risk_gt_fields": ["delivery_time_range","customs_clearance_capability","pricing_model","insurance_policy"],
        "industry_specific_fields": {"service_regions":"服务区域覆盖","shipping_lanes":"运输线路","delivery_time_range":"时效范围","customs_clearance_capability":"清关能力","warehouse_network":"仓储网络","insurance_policy":"保险政策","tracking_system":"追踪系统","compliance_documents":"合规文件"},
        "kpi_weights": {"accuracy_rate":0.25,"scenario_recall":0.15,"recommendation_quality":0.15,"citation_rate":0.15,"completeness_rate":0.10,"sov":0.10,"first_rec_rate":0.05,"cross_platform_consistency":0.05},
        "competitor_rules": {"direct":["同线路","同服务区域","同货物类型","同客户规模"],"substitute":["自有物流","FBA等平台物流","邮政小包"],"wrong_competitor_types":["船公司","航空公司","港口运营商"]},
        "risk_rules": [
            {"term":"100%清关","risk_level":"P0","risk_type":"service_guarantee","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"清关无法100%保证"},
            {"term":"绝对准时","risk_level":"P0","risk_type":"service_guarantee","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"时效不可绝对化"},
            {"term":"免税保证","risk_level":"P1","risk_type":"tax_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"税务以海关为准"},
            {"term":"最低价保证","risk_level":"P1","risk_type":"pricing_claim","match_type":"exact","applies_to":["generated_content"],"action":"review","explanation":"价格声称需核实"},
            {"term":"官方合作无来源","risk_level":"P1","risk_type":"partnership_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需合作证明"},
            {"term":"全球覆盖","risk_level":"P2","risk_type":"coverage_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需具体覆盖国家清单"},
            {"term":"当天达","risk_level":"P2","risk_type":"delivery_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"review","explanation":"时效以实际线路为准"},
            {"term":"包税双清","risk_level":"P2","risk_type":"customs_claim","match_type":"exact","applies_to":["generated_content"],"action":"review","explanation":"清关政策以海关为准"},
            {"term":"全程冷链","risk_level":"P2","risk_type":"service_claim","match_type":"exact","applies_to":["ai_response"],"action":"review","explanation":"冷链覆盖需核实"},
            {"term":"丢件必赔","risk_level":"P1","risk_type":"insurance_claim","match_type":"exact","applies_to":["generated_content"],"action":"review","explanation":"赔偿条款以合同为准"},
        ],
        "compliance_constraints": {"forbidden_claims":["100%清关","绝对准时"],"required_disclaimers":["具体时效/费用/清关政策以实际线路和海关为准"],"source_required_rules":{"delivery_time_range":"official","customs_clearance_capability":"official","pricing_model":"official"},"review_required_rules":["涉及时效/清关/费用的声明需核实"],"content_generation_constraints":["不得承诺清关成功率","不得虚构税务优惠","不得虚构官方合作","涉及跨境政策需引用官方"]},
        "content_templates": {"service_lanes":{"title":"服务线路页","target_gt_fields":["shipping_lanes","service_regions"]},"customs_page":{"title":"清关能力说明页","target_gt_fields":["customs_clearance_capability"]},"delivery_faq":{"title":"时效范围FAQ","target_gt_fields":["delivery_time_range"]},"warehouse_page":{"title":"海外仓网络页","target_gt_fields":["warehouse_network"]}},
        "action_rules": {}, "review_rules": {},
    },
    {
        "slug": "ai_cloud_devtools", "name": "AI/云计算/开发者工具", "level": "domain", "domain": "ai_cloud_devtools",
        "description": "AI平台、云服务、API服务、开发者工具、数据平台、MLOps",
        "business_model_tags": ["subscription","api_first","developer_ecosystem"],
        "required_gt_fields": ["official_name","core_capabilities","api_docs","pricing_model","deployment_options","developer_support","security_certifications","official_domains","open_source_license","sla"],
        "high_risk_gt_fields": ["core_capabilities","api_docs","security_certifications","sla","open_source_license"],
        "industry_specific_fields": {"core_capabilities":"核心能力","api_docs":"API文档","deployment_options":"部署方式(云/私有/混合)","developer_support":"开发者支持","open_source_license":"开源许可","model_capabilities":"模型能力","integration_ecosystem":"集成生态","sla":"服务水平协议"},
        "kpi_weights": {"accuracy_rate":0.20,"differentiation":0.20,"recommendation_quality":0.15,"citation_rate":0.15,"scenario_recall":0.10,"completeness_rate":0.10,"sov":0.05,"first_rec_rate":0.05},
        "competitor_rules": {"direct":["同技术栈","同开发者场景","同API能力","同部署方式"],"substitute":["开源方案","自研","传统软件"],"wrong_competitor_types":["咨询公司","系统集成商","培训机构"]},
        "risk_rules": [
            {"term":"百分百准确","risk_level":"P0","risk_type":"accuracy_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"AI不存在百分百准确"},
            {"term":"完全替代工程师","risk_level":"P1","risk_type":"automation_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"AI辅助而非替代"},
            {"term":"永久免费","risk_level":"P1","risk_type":"pricing_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"review","explanation":"定价以官方为准"},
            {"term":"官方开源无证据","risk_level":"P1","risk_type":"license_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需开源仓库验证"},
            {"term":"无限调用","risk_level":"P2","risk_type":"pricing_claim","match_type":"exact","applies_to":["generated_content"],"action":"review","explanation":"API限额以官方为准"},
            {"term":"无数据风险","risk_level":"P0","risk_type":"security_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"block","explanation":"数据安全不可绝对化"},
            {"term":"99.99%可用性","risk_level":"P2","risk_type":"sla_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"review","explanation":"SLA需官方公布"},
            {"term":"无需代码","risk_level":"P1","risk_type":"ease_of_use_claim","match_type":"exact","applies_to":["generated_content"],"action":"review","explanation":"低代码/无代码需说明限制"},
            {"term":"毫秒级响应","risk_level":"P2","risk_type":"performance_claim","match_type":"semantic","applies_to":["ai_response"],"action":"review","explanation":"响应时间需标注条件"},
            {"term":"企业级安全","risk_level":"P2","risk_type":"security_claim","match_type":"exact","applies_to":["generated_content"],"action":"review","explanation":"需具体认证"},
        ],
        "compliance_constraints": {"forbidden_claims":["百分百准确","无数据风险","完全替代人工"],"required_disclaimers":["具体功能和性能以官方文档为准"],"source_required_rules":{"security_certifications":"official_or_cert_body","sla":"official","open_source_license":"official_or_github"},"review_required_rules":["涉及AI能力/安全/SLA的声明需核实"],"content_generation_constraints":["不得虚构开源许可","不得虚构API能力","不得虚构SLA","不得夸大模型准确率和安全性"]},
        "content_templates": {"api_docs_entry":{"title":"API文档入口页","target_gt_fields":["api_docs"]},"quickstart_page":{"title":"开发者快速开始页","target_gt_fields":["core_capabilities","developer_support"]},"model_page":{"title":"模型能力说明页","target_gt_fields":["model_capabilities"]},"pricing_faq":{"title":"价格与限额FAQ","target_gt_fields":["pricing_model"]},"security_page":{"title":"安全合规说明页","target_gt_fields":["security_certifications"]}},
        "action_rules": {}, "review_rules": {},
    },
    {
        "slug": "beauty_fashion", "name": "美妆个护与时尚生活", "level": "domain", "domain": "beauty_fashion",
        "description": "美妆、护肤、个护、服饰、奢侈品、生活方式品牌",
        "business_model_tags": ["consumer_brand","lifestyle","trend_sensitive"],
        "required_gt_fields": ["official_name","product_categories","ingredients","target_skin_or_user_type","price_band","usage_scenarios","official_channels","official_domains","safety_testing","return_policy"],
        "high_risk_gt_fields": ["ingredients","safety_testing","product_categories"],
        "industry_specific_fields": {"ingredients":"成分说明","target_skin_or_user_type":"适用肤质/人群","usage_scenarios":"使用场景","official_channels":"官方购买渠道","safety_testing":"安全性测试","brand_style":"品牌风格定位"},
        "kpi_weights": {"scenario_recall":0.25,"recommendation_quality":0.20,"accuracy_rate":0.15,"sov":0.15,"completeness_rate":0.10,"citation_rate":0.05,"first_rec_rate":0.05,"differentiation":0.05},
        "competitor_rules": {"direct":["同品类","同价位","同目标人群","同风格定位"],"substitute":["药妆","医美","平替品牌","二手奢侈品"],"wrong_competitor_types":["原料供应商","代工厂","美容院"]},
        "risk_rules": [
            {"term":"立刻美白","risk_level":"P0","risk_type":"efficacy_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"化妆品不得承诺立竿见影"},
            {"term":"永久抗衰","risk_level":"P0","risk_type":"efficacy_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"夸大抗衰老功效"},
            {"term":"医学认证无证据","risk_level":"P0","risk_type":"certification_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"block","explanation":"化妆品非药品不得声称医学认证"},
            {"term":"明星代言虚构","risk_level":"P1","risk_type":"endorsement_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需确认代言关系"},
            {"term":"无任何副作用","risk_level":"P0","risk_type":"safety_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"任何产品都可能过敏"},
            {"term":"纯天然","risk_level":"P2","risk_type":"ingredient_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"review","explanation":"需成分表验证"},
            {"term":"七天见效","risk_level":"P2","risk_type":"efficacy_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"review","explanation":"功效声称需测试数据"},
            {"term":"人人适用","risk_level":"P1","risk_type":"safety_claim","match_type":"exact","applies_to":["generated_content"],"action":"review","explanation":"需标注适用人群和过敏提示"},
            {"term":"正品保证","risk_level":"P2","risk_type":"authenticity_claim","match_type":"exact","applies_to":["ai_response"],"action":"review","explanation":"需正品溯源"},
            {"term":"年度最佳","risk_level":"P2","risk_type":"award_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"奖项需来源"},
        ],
        "compliance_constraints": {"forbidden_claims":["立刻美白","永久抗衰","医学认证","无任何副作用"],"required_disclaimers":["效果因人而异","如有不适请停止使用","化妆品不能替代药品"],"source_required_rules":{"ingredients":"official","safety_testing":"official_or_lab"},"review_required_rules":["涉及功效/成分/安全性的声明需谨慎表述"],"content_generation_constraints":["不得夸大功效","不得虚构成分功效","不得虚构代言和奖项","涉及敏感功效需谨慎"]},
        "content_templates": {"ingredients_page":{"title":"成分说明页","target_gt_fields":["ingredients"]},"skin_type_faq":{"title":"适合肤质FAQ","target_gt_fields":["target_skin_or_user_type"]},"official_channels_page":{"title":"官方购买渠道页","target_gt_fields":["official_channels","official_domains"]},"scenario_page":{"title":"产品使用场景页","target_gt_fields":["usage_scenarios"]}},
        "action_rules": {}, "review_rules": {},
    },
    {
        "slug": "public_sector_city", "name": "政府公共服务与城市品牌", "level": "domain", "domain": "public_sector_city",
        "description": "政务服务、城市品牌、园区招商、公共机构、公共服务平台",
        "business_model_tags": ["public_sector","official","policy_driven"],
        "required_gt_fields": ["official_name","official_government_site","service_scope","policy_documents","application_process","eligibility_criteria","contact_channels","service_locations","public_notice_sources","investment_policy"],
        "high_risk_gt_fields": ["policy_documents","application_process","eligibility_criteria","investment_policy","official_government_site"],
        "industry_specific_fields": {"official_government_site":"官方政府网站","service_scope":"服务范围","policy_documents":"政策文件","application_process":"办事流程","eligibility_criteria":"资格条件","contact_channels":"联系方式与渠道","service_locations":"服务地点","investment_policy":"招商政策"},
        "kpi_weights": {"accuracy_rate":0.35,"citation_rate":0.25,"completeness_rate":0.15,"semantic_stability":0.10,"cross_platform_consistency":0.05,"sov":0.05,"first_rec_rate":0.03,"scenario_recall":0.02},
        "competitor_rules": {"direct":["同区域","同服务类型","同招商对象"],"substitute":["上级政府平台","商业服务平台"],"wrong_competitor_types":["商业公司","非政府机构"]},
        "risk_rules": [
            {"term":"保证审批通过","risk_level":"P0","risk_type":"policy_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"不得承诺审批结果"},
            {"term":"官方补贴必得","risk_level":"P0","risk_type":"policy_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"block","explanation":"补贴以政策为准"},
            {"term":"政策无条件适用","risk_level":"P0","risk_type":"policy_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"block","explanation":"政策有具体条件和流程"},
            {"term":"虚构政策","risk_level":"P0","risk_type":"fabricated_info","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"block","explanation":"不得虚构政策文件"},
            {"term":"虚构政府背书","risk_level":"P0","risk_type":"endorsement_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"block","explanation":"不得虚构政府认可"},
            {"term":"免费用","risk_level":"P1","risk_type":"pricing_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"公共服务费用以官方为准"},
            {"term":"一站式","risk_level":"P2","risk_type":"service_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"review","explanation":"服务范围以官方为准"},
            {"term":"税收优惠","risk_level":"P1","risk_type":"policy_claim","match_type":"exact","applies_to":["ai_response","generated_content"],"action":"review","explanation":"税收政策以税务部门为准"},
            {"term":"落户政策","risk_level":"P1","risk_type":"policy_claim","match_type":"semantic","applies_to":["ai_response"],"action":"review","explanation":"落户政策以公安和人社为准"},
            {"term":"土地价格","risk_level":"P2","risk_type":"pricing_claim","match_type":"semantic","applies_to":["ai_response","generated_content"],"action":"review","explanation":"土地价格以国土部门为准"},
        ],
        "compliance_constraints": {"forbidden_claims":["保证审批通过","官方补贴必得","虚构政策","虚构政府背书"],"required_disclaimers":["政策信息以政府官方发布为准","具体办事流程请咨询官方渠道"],"source_required_rules":{"policy_documents":"official_government","application_process":"official_government","eligibility_criteria":"official_government"},"review_required_rules":["涉及政策/审批/补贴的声明必须引用政府官方来源"],"content_generation_constraints":["政策信息必须引用官方来源","不得承诺审批结果","不得虚构补贴和优惠","不得混淆办事流程和机构职责"]},
        "content_templates": {"process_page":{"title":"官方办事流程页","target_gt_fields":["application_process","eligibility_criteria"]},"policy_faq":{"title":"政策FAQ","target_gt_fields":["policy_documents"]},"investment_page":{"title":"招商政策说明页","target_gt_fields":["investment_policy"]},"contact_page":{"title":"联系方式与渠道页","target_gt_fields":["contact_channels","service_locations"]}},
        "action_rules": {}, "review_rules": {"policy_claim":"legal_reviewer+admin","government_claim":"legal_reviewer"},
    },
]
